### ISSUE TITLE
Feature Request: PTH

### ISSUE THREAD

**Issue by Raikia** [ropnop/go-windapsearch#1]
Not sure if its possible, but it would be awesome to have the ability to use NTLM hashes (PTH) instead of only plaintext passwords.

**Comment by ropnop** [comment]
Aw man why you gotta nerd snipe me like that? Now i'm totally going to start looking up how to do PTH in Golang. No promises, but great idea

**Comment by Raikia** [comment]
This is an **AWESOME** project though.  10/10 fantastic

**Comment by ropnop** [comment]
v0.2 released with PtH support! Lmk if it’s working for you (I’ve tested in my lab) and if so I’ll close this out

**Comment by dvs17** [comment]
This works for me!
