### ISSUE TITLE
Unable to run multiple modules in the same command

### ISSUE THREAD

**Issue by tuv7041** [ropnop/go-windapsearch#11]
Hi, in python's version of windapsearch I was able to run multiple modules at once (eg. unconstrained user-spns privileged-users domain-admins). I tried it with go's version and it seems that if you specify multiple modules, it only takes into account the first one. Am I doing something wrong? 

Thanks!

**Comment by ropnop** [comment]
Hi! You’re not doing anything wrong, I didn’t copy that functionality over from the Python one. With the new JSON encoding it’s really difficult to combine outputs from different queries in the same response (for example, Groups and Users have very different attributes)

With the python version, it was basically just making sequential full connections and requests, so with the go version it wouldn’t be much different than just running `./windapsearch -m mod1 && ./windapsearch -m mod2`, but I know that’s not ideal. 

What are some of the common combinations of modules you run? Maybe they could be combined into a “super” module that executes multiple filters in an “OR”?

**Comment by tuv7041** [comment]
Hey Ronnie! Sorry for the delay, the notification about your reply somehow got lost on my inbox. I usually combine the enumeration of specific things that are good for quick wins. Eg: unconstrained delegations, user-spn, privileged users and domain admins. But its not really that big of an issue, I just wanted to ask in case I was doing something wrong, but I can definitely concatenate commands. I understand the difficulties of working with JSON encoding. 
Thanks for the reply!
