### ISSUE TITLE
Error with anonymous bind

### ISSUE THREAD

**Issue by CarterMcKelvain** [ropnop/go-windapsearch#4]
Hi there, I'm seeing an issue with how the latest release handles anonymous binds. Below is a screenshot from the latest release as well as the older release. Both are against the same system. 

I *think* that commit https://github.com/ropnop/go-windapsearch/commit/d58f29e1a362838ca51b8bd4be9c71e3f22e3df8 is causing this, but I'm not positive.  That, or I'm not doing something correctly, ha!

![pic](https://user-images.githubusercontent.com/11194109/84573217-16931580-ad6d-11ea-8ca5-0961cc309b9c.jpg)

**Comment by ropnop** [comment]
Yikes yep I totally broke it. Should be an easy fix - are you able to download the branch in #5 and build locally to try it out?

**Comment by CarterMcKelvain** [comment]
Yep! Just did and it works as expected now, thanks! 👍 
![pic1](https://user-images.githubusercontent.com/11194109/84574495-c61fb600-ad74-11ea-935c-74798ef99850.jpg)
